repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: [--maxkb=2048]
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
    -   id: autopep8

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
        
-   repo: https://github.com/kynan/nbstripout
    rev: v0.3.0
    hooks:
    -   id: nbstripout
        args: [--keep-output]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        additional_dependencies: [sqlalchemy-stubs]
        
-   repo: https://github.com/iterative/dvc
    rev: v1.11.16
    hooks:
    -   id: dvc-pre-commit
        language_version: python3
        stages:
        -   commit
    -   id: dvc-pre-push
        additional_dependencies: ['.[all]']
        language_version: python3
        stages:
        -   push
    -   always_run: true
        id: dvc-post-checkout
        language_version: python3
        stages:
        -   post-checkout
